{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "temp.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    release: prometheus
    {{- include "temp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "temp.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
{{- end }}
